# -*- coding: utf-8 -*-
"""seco_procesado_muestras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5ClhcOSoKaNqokZOMAJJv0_xYTzGk98
"""

"""
borra todo workspace colab, configura una nueva estructura de archivos
e importa último documento de medidas obtenidas del UART 
"""
!rm -rf *
!mkdir -p tty raw processed
!wget --output-document gh.zip https://github.com/margobra8/seco/archive/refs/heads/main.zip
!unzip -j gh.zip "seco-main/measurements/last/*" -d "./tty"
!rm gh.zip

# librería de procesamiento numérico
import numpy as np

# genera varios archivos, de cada run (tirada de todas las tensiones) extrae los 12 experimentos
lns = []

for k in range(10):
  with open(f"./tty/secoTTY_run{k+1}_p.log", "r") as f:
    l = f.readlines()
    lns.append(len(l))
    for i in range(12):
      for (idx, line) in enumerate(l):
        if f"Experiment {i+1}\n" == line:
          #print(line)
          with open(f"./raw/secoRaw_run{k+1}_{i+1}V_p.data", "w") as fw:
            fw.writelines(l[idx+1:idx+1202])

assert len(set(lns)) <= 1 #comprobar que todas las runs tienen el mismo numero de samples y que se ha sampleado bien

# genera los archivos de media .mean
d = np.zeros((12, 1201, 10))

for run_no in range(10):
  for v in range(12):
    with open(f"./raw/secoRaw_run{run_no+1}_{v+1}V_p.data", "r") as fe:
      le = fe.readlines()
      for l in le:
        if l:
          #print(l)
          proc_line = l.split()
          #print(f"./raw/medidas_{run_no+1}_p_exp_{v+1}V.data")
          sample_no = int(proc_line[0])
          enc_val = float(proc_line[1])
          d[v][sample_no][run_no] = enc_val

means = np.mean(d, axis=2)

print(means.shape)

for v in range(12):
  with open(f"./processed/secoData_{v+1}V.mean", "w") as fm:
    for (s, e) in enumerate(means[v]):
      fm.write(f"{str(s)} {str(e)}\n")

# genera un zip con todos los archivos generados
!zip -r /home/secoAll.zip /content/processed /content/raw /content/tty

# descarga el zip generado
from google.colab import files
files.download("/home/secoAll.zip")